/** Cloudflare native rate-limit binding (see wrangler.toml [[unsafe.bindings]]). */
export interface RateLimiterBinding {
  limit(options: { key: string }): Promise<{ success: boolean }>;
}

export interface Env {
  /** Surfaced by GET /version; bumped in wrangler.toml alongside package.json. */
  SERVER_VERSION?: string;
  /** Native per-colo rate limiter; optional (in-memory bucket is the fallback). */
  RATE_LIMITER?: RateLimiterBinding;
  /**
   * Per-tool kill switch: comma-separated tool names to disable instantly (see
   * wrangler.toml [vars]). Disabled tools leave tools/list and answer
   * tools/call with a fixed "temporarily offline" message.
   */
  DISABLED_TOOLS?: string;
  /**
   * Exact public token generated by the OpenAI Plugins submission portal.
   * It is served as plain text from /.well-known/openai-apps-challenge.
   */
  OPENAI_APPS_CHALLENGE?: string;
}
